### ISSUE TITLE
ISO27002-2022 Mapping

### ISSUE THREAD

**Issue by TomCorremans** [center-for-threat-informed-defense/top-attack-technique#1]
Hi,

Are there any plans for a mapping for ATT&CK to ISO27002-2022 in the calculator?

Or can I possibly contribute to this? How would this work in practice?

Thanks in advance.

**Comment by mticmtic** [comment]
Hey Tom, we don't currently have plans to map to ISO27002 on our roadmap. We are planning an update for late fall to address many community-sourced improvements and this could be one of them. We would be happy if you wanted to contribute. Maybe a meeting to discuss the use case and to make sure we could include it in our next release. I will email you to discuss further.
