### ISSUE TITLE
A short review and experiences of using the tool

### ISSUE THREAD

**Issue by olympiador** [center-for-threat-informed-defense/top-attack-technique#3]
First, a few words about my professional experience, as well as in the context of Mitre Att&ck - so you can better understand where my questions and doubts about this project come from. So:

**Introduction**
I have more than 10 years of experience in IT administration with security elements, plus about 3 years typically in pure security. I have a fairly broad range of knowledge but not specialized - i.e. I'm skilled in Windows, Linux, data-center, networking, virtualization, processes and documentation. One of the important impulses to move into security (besides wanting to grow) was boredom with technology, so I liked governance and compliance. I've worked in a fairly limited capacity with one SIEM product so far and have become more or less familiar with it. I don't have much experience with Threat intelligence or threat hunting.
How I came across your project: since I met Mitre Att&ck a few years ago, I immediately came to the conclusion that the key in it is to select specific TTPs for the organization I work for and plan defense mechanisms based on that. You Americans have a word like "daunting," and it perfectly captures what I feel when I look at possible attack paths for organizations. It's a feeling that makes me feel I need help in prioritizing what I should do first to protect the organization. I wanted to use your tool for this purpose, and below are my impressions and thoughts.

**"Top 10 techniques" worksheet**
A general question about this sheet: I'm guessing it's about coverage of different security categories in our SOC operations? If so, how can I determine the coverage of each category in the SOC when we are just implementing it? It should be stated somewhere that the worksheet is only useful if we have and operating SOC.
1 PROCESS coverage:
What exactly do you mean by "PROCESS coverage"? It's possible that I'm too unfamiliar with Att&ck but I don't associate a definition of the term or such a category. My only guess is that it means - in conjunction with the "Coverage definitions" sheet) how we monitor the various aspects of security in our SOC? If so, what does not having SIEM (No coverage) mean in the context of PROCESS?
2. NETWORK coverage
What exactly is NETWORK coverage? Is it about events and flows flowing down from network devices, and the alerts generated from them? 
3. FILE coverage
What exactly is FILE coverage? Is it about DLP systems and related events reported to the SIEM?
4. CLOUD coverage
What is included in CLOUD coverage? How do I differentiate between cloud and on-prem events when I have a hybrid solution? Does the cloud model matter?
5 HARDWARE coverage
Is it about subordinate infrastructure a.k.a. devices in the datacenter?

**"Coverage definitions" worksheet.**
I think the long, wordy descriptions in column B could be replaced by a few supporting questions:
B5, for example, could be broken down like this:
Consider your level as Medium if you answered "Yes" to most of these questions:
- Do you have an effective team to automate rules/queries?
- Do you have tools helping you correlate and integrate numerous data types across all your endpoints in order to filter out noise and potential false positives?
- Do you have at least one (even at a basic level) Data Science capability provided by your tools (i.e ELK Enterprise) that helps you make sense of all data in an automatic or semi-automatic way?
...

**Algorithm for top techniques:**
1. I filled cells B15:B19 with "l, n, n, n, n, n" values. WMI popped out as the first techniqe. 
- What if I don't have Windows in the environment at all?
- What if I already have WMI covered to such an extent and want to cross it out of my top 10? I know I can sort the relevant column by value, or change the parameters that calculate one of the top 9, but it would be nice to be able to simply put a checkmark next to the "Disregard" technique.
2. the A3:A12 values are worth rounding to 2 decimal places, maybe even one. 
3. column B3:B12 could have links to techniques right away - preferably right to the Mitre page, that way you won't have to update the "techniques" sheet every time something changes there.
And it would be even better if the link to a technique took me straight to the assigned defense mechanisms from D3fend. Also to their site, of course, so that I don't have to maintain it in the sheet.

**Wording**:
- What is a choke point in your understanding? I became familiar with the term relatively recently, as I started working a few months ago in a multinational corporation, where the term is used quite freely. Nevertheless, being in the security industry for several years, I am only now coming across the term. What's missing is a definition of what it basically is (plus some examples).

And that's it for now, thanks for your work - I appreciate it - but unfortunately I can't judge whether the tool is useful to me because I don't fully understand the terminology in it.

**Comment by mticmtic** [comment]
Hi @olympiador, I appreciate your thoughts and feedback on this project. Here is my response:

`It should be stated somewhere that the worksheet is only useful if we have and operating SOC.` You wouldn't need a SOC, specifically, but you would need some of the capabilities of a SOC, such as detections and alerts. But your question leads me to an interesting observation that there are a lot of ATT&CK techniques you can prevent without ever having to detect them. I will think on that some more and how it affects Top ATT&CK Techniques.

For your other questions, I'd recommend checking out the methodology portion of our website [here](https://top-attack-techniques.mitre-engenuity.org/methodology). If you still have questions after reading through that, you can [email me](mailto:ctid@mitre-engenuity.org) and I'd be happy to continue this conversation.

-Mike
