### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by robocop-bob** [center-for-threat-informed-defense/top-attack-technique#6]
broken link to Methodology input file 

<img width="1712" alt="Zrzut ekranu 2023-11-28 o 10 18 26" src="https://github.com/center-for-threat-informed-defense/top-attack-techniques/assets/3903647/b69d2284-c11c-4f48-997b-e38f18a53c2f">

**Comment by mticmtic** [comment]
@robocop-bob Thank you for pointing that out. A local path was accidentally referenced and we are working getting that fixed.

**Comment by mehaase** [comment]
Thank you for reporting this, @robocop-bob. The Excel file is fixed now.
